### ISSUE TITLE
how to change endpoint type to ENGINEIO.

### ISSUE THREAD

**Issue by rohitmishra4444** [deepstreamIO/deepstream.io-client-ios#1]

**Comment by yasserf** [comment]
We don't support engineIO currently in mobile sdks since have moved to pure websockets.

This change will be in offical releases by the end of this month, and RC before that

**Comment by rohitmishra4444** [comment]
Also login not working on localhost only works on "dashboard-ds-dev.deepstreamhub.com:6021"
stucks on incoming TCP connection.

**Comment by akramhussein** [comment]
Hi @rohitmishra4444 - which server are you using? Mac/Docker etc?

How are you logging in? There is an example I've just published [here](https://github.com/akramhussein/ds-demo-pizza-tracker/tree/master/ios/PizzaTracker) that logs in and I've just tested it with the Mac server and works fine using 0.0.0.0:602[1/0].

**Comment by rohitmishra4444** [comment]
Using deepstream version '0.9.0' and testing on ios emulator and tried changing localhost to ip but still not been able to login.

**Comment by akramhussein** [comment]
Would you be able to copy in the console output?

**Comment by rohitmishra4444** [comment]
connects easily with "dashboard-ds-dev.deepstreamhub.com:6021" but nothing happens when i put localhost instead of deepstreamhub.

**Comment by akramhussein** [comment]
Hi @rohitmishra4444, please see the latest update and Example. 
Try "0.0.0.0:6020".

**Comment by akramhussein** [comment]
@yasserf I think this can be closed?

**Comment by yasserf** [comment]
Yup!
